---
# Here belong all actions like service-restart,
# config-file loads, etc. that will be started
# if a change on a task was made

- name: reload nginx
  service:
    name: nginx
    state: reloaded

...