---
# Add all dependent roles, that should be executed before
# the content of this role. If this is an appliance
# there should always be atleast these 3 includes

# Change needed roles here
- name: download dependencies from galaxy
  shell: ansible-galaxy install melvin_suter.os_basic uniqconsulting.open_vm_tools melvin_suter.firewall melvin_suter.nginx melvin_suter.php melvin_suter.mariadb

# Include all roles like this:

- name: uniqconsulting.os_basic
  include_role:
    name: uniqconsulting.os_basic
  vars:
    setup_selinux: true
    selinux_policy: disabled
    setup_firewalld: false
    setup_iptables: true
    os_update: true
    package_cleanup: true
    package_upgrade: all
    epel_repo: true

- name: uniqconsulting.open_vm_tools
  include_role:
    name: uniqconsulting.open_vm_tools
  when: install_openvmtools
      
- name: uniqconsulting.firewall
  include_role:
    name: uniqconsulting.firewall
  vars:
    firewall_open_ports: "{{ role_ports + additional_open_ports }}"

- name: melvin_suter.mariadb
  include_role:
    name: melvin_suter.mariadb

- name: create nginx user (needed for php)
  user:
    name: nginx
    system: yes
    shell: /usr/sbin/nologin
    create_home: no
  
- name: melvin_suter.php
  include_role:
    name: melvin_suter.php
  
- name: melvin_suter.nginx
  include_role:
    name: melvin_suter.nginx
  vars: 
    nginx_vhosts: []
    nginx_default_document_root: "{{ webserver_document_root }}"
      
...